### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by samma835** [rajubd49/PDFViewer#1]
Thanks. This repo is so cool! I put it into my project and it runs well.

One thing, it will be more perfect if it can support fullscreen view mode.

**Comment by janbildsoehansen** [comment]
Nice work 
works like a charme much appreciated 

have a question can you make the white background on the pages thumbnail transparent..??

**Comment by rajubd49** [comment]
> Thanks. This repo is so cool! I put it into my project and it runs well.
> 
> One thing, it will be more perfect if it can support fullscreen view mode.

Thanks, I'm happy that this repo helps you somehow. If you check the code, you will see that the PDFView is actually a fullscreen view. I did enable "autoScales" property which will scale your pdf file properly in the view. Full-screen mode also depends on your pdf file too. So this approach seems better for me, if I scale the pdf file to fit full screen all the time then it may break for some portion of pdf content sometime. Hope you understand what I'm trying to say :)

**Comment by rajubd49** [comment]
> Nice work
> works like a charme much appreciated
> 
> have a question can you make the white background on the pages thumbnail transparent..??

Thanks, I'm happy that this repo helps you somehow.

I did update the repo for your convenience, please check version 1.0.2 for this update.

**Comment by janbildsoehansen** [comment]
nice thanks much appreciated

**Comment by samma835** [comment]
You're right. Thanks.
